config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
        resources :likes, only: [:new, :create, :destroy]
    end
  end

  namespace :api do
    resources :users, only: [:show] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user.admin?
      can :manage, :all
    else
      can :create, [Post, Comment]
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy, foreign_key: 'post_id'
  has_many :comments, dependent: :destroy, foreign_key: 'post_id'

  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'user_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def admin?
    role == 'Admin'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    @comments = Comment.where(post_id: params[:post_id]).order(id: :asc)
    render json: @comments, status: :ok
  end

  def create
    @comment = Comment.new(user_id: current_user.id, post_id: comment_params[:post_id], text: comment_params[:text])

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.permit(:text, :post_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id]).order(id: :asc)
    render json: @posts, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password, :role) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.user = current_user
    @comment.post_id = @post.id

    if @comment.save
      flash[:success] = 'Comment created successfully!'
      redirect_to user_post_path(user_id: @comment.user_id, id: @comment.post_id)
    else
      flash[:alert] = 'Error: could not create comment'
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.post.decrement!(:comments_counter)
    @comment.destroy!
    flash[:success] = 'Comment was deleted successfully!'
    redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(user_id: current_user.id, post_id: @post.id)
    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      flash[:alert] = 'Error: could not add like'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = User.find(params[:user_id])
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(id: @post.id)
    else
      flash[:alert] = 'Error: could not create a new post'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    @post.destroy!
    flash[:success] = 'Post was deleted successfully!'
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="new-post-section">
  <div class="new-post-container">
    <h1>Add a new comment</h1>
    <%= form_with model: @comment, url: user_post_comments_path do |c| %>
      <div class="text-container">
        <%= c.label :text%>
        <%= c.text_area :text, cols: 30, rows:1%><br>
      </div>
      <%= c.submit "Submit", class:"new-post-btn submit-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PenIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete } %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_user.html.erb
<%= link_to user do %>
   <li class="user-card">
     <div class="user-img">
       <img src="<%= user.photo %>" class="user-photo">
     </div>
     <div class="user-info">
       <h2><%= user.name %></h2>
       <h2 class="post-counter"> Number of posts: <%= user.posts_counter%></h2>
     </div>
   </li>
 <% end %>

app/views/posts/index.html.erb
<h1 class="post-title"><%= @user.name%>'s Posts</h1>
<section class='user-card-container'>
  <section class = "user-card">
    <div class="user-img">
      <img src="<%= @user.photo %>" width="100px"  height = "100px" class="user-photo">
    </div>
    <div class="user-info">
      <h1><%= @user.name %></h1>
      <h2 class="post-counter"> Number of posts: <%= @user.posts_counter%></h2>
    </div>
  </section>
  <section class = "user-bio">
    <p><%= @user.bio %></p>
  </section>
  
  <section class='post-container'>
    <% @posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.author_id, id: post.id) do%>
        <div class="post-card-container">
          <div class="post-card">
            <h4><%= post.title %></h4>
            <p><%= post.text %></p>
            <div class="reactions">
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %></span>
            </div>
          </div>
          <h4 class="comment-title">Comments</h4>
          <div class="comment-container">
            <% post.recent_comments.each do |comment|%>
              <span><p><%= comment.user.name %>: <%= comment.text%></p></span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </section>
  <div>
  <% if (can? :create, Post) && current_user.id == @user.id %>
    <%= link_to 'Add a New Post', new_user_post_path(user_id: @user.id), class: "new-post-btn post-btn" %>
  <% end %>
    <a class='pagination-btn' href='#'>Pagination</a>
  </div>
</section>

app/views/posts/new.html.erb
<section class="new-post-section">
  <section class="new-post-container">
    <h1>Add a new post</h1>
    <%= form_with model:[current_user, current_user.posts.build] do |form|%>
      <% @post.errors.full_messages do |msg|%>
        <p><%= msg %></p>
        <% end %>
      <%= form.label :title%>
      <%= form.text_field  :title%><br>
      <div class="text-container">
        <%= form.label :text%>
        <%= form.text_area :text, cols:40, row:1%>
      </div>
      <%=form.submit "Submit", class:"new-post-btn submit-btn"%>
    <% end%>
  </section>
</section>

app/views/posts/show.html.erb
<section class = "post-container">
    <section class = "post-header">
      <h2><%= @post.title %> by <%= @post.author.name%></h2>
      <div>
        <span>Comments: <%= @post.comments_counter%></span>
        <span>Likes: <%= @post.likes_counter%></span>
      </div>
    </section>
      <div class = "post-body">
        <p><%=@post.text %></p>
        <% if can? :destroy, @post %>
        <%= form_with model: @post, url: user_post_path(@post.author, @post), method: :delete do |f| %>
          <%= f.submit "Delete Post" %>
        <% end %>
      <% end %>
      </div>
      <h4 class="comment-title">Comments</h4>
    <div class="comment-container">
      <%@post.comments.each do |comment|%>
        <p><strong><%= comment.user.name%></strong>:<%= comment.text%></p>
        <% if can? :destroy, comment %>
          <%= form_with model: @comment, url: user_post_comment_path(@post.author, @post, comment), method: :delete do |f| %>
            <%= f.submit "Delete Comment" %>
        <% end %>
      <% end %>
      <%end%>
    </div>
    <div class="like-comment-container">
      <%= form_with model: @like, url:user_post_likes_path(post_id: @post.id) do |l| %>
        <%= l.submit  "Like", class:"new-post-btn submit-btn"%>
      <% end %>
      
      <% if can? :create, Comment %>
        <%= link_to 'New Comment', new_user_post_comment_path(@post.author, @post) %>
      <% end %>
    </div>
</section>

app/views/users/index.html.erb
<h1 class= "user-title">Welcome to User Page</h1>
<div class="user-container">
  <ul>
    <%= render partial:'partials/user', collection:@users%>
  </ul>
</div>

app/views/users/show.html.erb
<section class = "user-profile">
    <section class = "user-card">
      <div class="user-img">
        <img src="<%= @users.photo %>" class="user-photo">
      </div>
      <div class="user-info">
        <h1><%= @users.name %></h1>
        <h2 class="post-counter"> Number of posts: <%= @users.posts_counter%></h2>
      </div>
    </section>
    
    <section class = "user-bio">
      <h5>Bio</h5>
      <%= @users.bio %>
    </section>
    <section class = "user-posts">
      <% @users.recent_posts.each do |post| %>
        <div class= "post">
          <h2><%= link_to post.title, user_post_path(post.author_id, post.id) %></h2>
          <p><%= post.text %></p>
          <div>
            <p>Comments: <%= post.comments_counter %></p>
            <p>Likes: <%= post.likes_counter %></p>
        </div>
      <% end %>
    </div>
    <%= link_to "See all posts", user_posts_path(user_id: @users.id), class: "all-post" %>
</section>